# Configuración global para el despliegue de tu sitio.

[build]
  # El comando que Netlify debe ejecutar para generar la carpeta 'dist'.
  command = "npm run build"
  
  # La carpeta que contiene los archivos finales listos para ser publicados.
  publish = "dist"

# Configuración para el manejo de rutas y SPA (Single Page Application).
# Esto es crucial para que las rutas internas de tu app funcionen.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200